### ISSUE TITLE
Folder configuration

### ISSUE THREAD

**Issue by GavinF17** [git-jock/jock-cli#2]
Enable folder configuration to be read from `~/.jockrc` and matched to folders passed into the CLI via the `--folder`/`-f` flag so that this can be passed to the plugins.

```yaml
folders:
  auth-service:
    location: /home/jock/git/authentication-service
  ...
  shared-entities:
    location: ~/shared-entities
```
