### ISSUE TITLE
Folder level plugin config

### ISSUE THREAD

**Issue by GavinF17** [git-jock/jock-cli#3]
Allow plugins to be configured at a folder level within `~/.jockrc`

This should match the plugin name to the config section so that it can be passed to the plugin later.

e.g. for git
```yaml
folders:
  jock-cli:
    location: /home/jock/git/jock-cli
    plugins:
      git:
        repository: git@github.com:git-jock/jock-cli.git
      [PLUGIN_NAME]:
        [PLUGIN_CONFIG_KEY]: PLUGIN_CONFIG_VALUE
        ...
```
